version: '3.8'

networks:
  product_network:
    driver: bridge

services:
  mongodb:
    image: 'mongo:6.0'
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - product_network
  
  number-generate-service:
    build: ./number-generate-service/
    restart: always
    container_name: number-generate-service
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    environment:
      JAVA_OPTS: '-Xmx1024m'
    networks:
      - product_network

  database:
    image: 'postgres:13'
    restart: always
    container_name: database
    networks:
      - product_network
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=products
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  
  orders_service:
    build: /Users/egor/Documents/itq/order-service
    restart: always
    container_name: order-service
    networks:
      - product_network
    ports:
      - "9091:9091"
    depends_on:
      - number-generate-service
      - database
    environment:
      JAVA_OPTS: '-Xmx1024m'

volumes:
  db-data: {}