version: '3.9'

services:
  mongodb:
    image: 'mongo:latest'
    container_name: number-mongodb
    restart: always
    ports:
      - "27017:27017"
  
  database:
    image: 'postgres:latest'
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
    ports:
      - "5432:5432"

  number-generate-service:
    build: ./orders/
    restart: always
    container_name: number-generate-service
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    environment:
      JAVA_OPTS: '-Xmx1024m'