openapi: "3.0.2"
info:
  title: Orders Service API
  version: "1.0"
servers:
  - url: https://localhost:9090/v1/

components:
  schemas:
    Error:
      description: "Ошибка"
      type: object
      properties:
        error:
          description: "error message"
          type: string

    order:
      description: "Заказ"
      type: object
      properties:
        id:
          description: "id Заказа в БД"
          type: integer
        number:
          description: "Номер заказа"
          type: string
        sum:
          description: "Сумма заказа"
          type: integer
        scale:
          description: "Масштаб суммы"
          type: integer
        orderDate:
          description: "Дата создания заказа. Например: 2017-07-21"
          type: string
          format: date
        recipient:
          description: "Информация о получателе"
          type: string
        address:
          description: "Информации об адресе доставки"
          type: string
        payment:
          description: "Тип оплаты"
          type: string
        delivery:
          description: "Тип доставки"
          type: string

    CreateOrderRequest:
      type: object
      properties:
        sum:
          type: integer
          format: int64
        scale:
          type: integer
          format: int64
        recipient:
          type: string
        address:
          type: string
        payment:
          type: string
        delivery:
          type: string
      required:
        - sum
        - scale
        - recipient
        - address
        - payment
        - delivery

    OrderResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        number:
          type: string
        sum:
          type: integer
          format: int64
        scale:
          type: integer
          format: int64
        orderDate:
          type: string
          format: date-time
        recipient:
          type: string
        address:
          type: string
        payment:
          type: string
        delivery:
          type: string

    ListOrdersResponse:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderResponse'
paths:
  /{id}:
    get:
      summary: Получить заказ по идентификатору
      operationId: getOrderById
      parameters:
        - name: id
          in: path
          required: true
          description: Идентификатор заказа
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Успешный ответ с деталями заказа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Заказ не найден

  /create:
    post:
      summary: Создать новый заказ
      operationId: createOrder
      requestBody:
        description: Информация о новом заказе
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
      responses:
        '200':
          description: Заказ успешно создан
        '404':
          description: Ошибка в запросе

  /get_by-date-and-sum:
    get:
      summary: Получить заказы по дате и сумме
      operationId: getOrdersByDateAndSum
      parameters:
        - name: currentDate
          in: query
          required: true
          description: Текущая дата
          schema:
            type: string
            format: date
        - name: sum
          in: query
          required: true
          description: Сумма заказа
          schema:
            type: integer
            format: int64
        - name: scale
          in: query
          required: true
          description: Точность
          schema:
            type: integer
      responses:
        '200':
          description: Успешный ответ со списком заказов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOrdersResponse'
        '404':
          description: Ошибка в запросе

  /get_without-order-between-dates:
    get:
      description: Получить заказы без заказа между датами
      parameters:
        - name: dateBefore
          in: query
          required: true
          description: Дата до
          schema:
            type: string
            format: date
        - name: dateAfter
          in: query
          required: true
          description: Дата после
          schema:
            type: string
            format: date
        - name: order
          in: query
          required: true
          description: Заказа
          schema:
            $ref: "#/components/schemas/order"
      responses:
        '200':
          description: Успешный ответ со списком заказов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOrdersResponse'
        '404':
          description: Ошибка в запросе
