version: '3.9'

services:
  mongodb:
    image: 'mongo:latest'
    container_name: number-mongodb
    restart: always
    ports:
      - "27017:27017"

  number-generate-service:
    build: .
    restart: always
    container_name: number-generate-service
    ports:
      - "9090:9090"
    depends_on:
      - mongodb
    environment:
      JAVA_OPTS: '-Xmx1024m'